### ISSUE TITLE
Odd bolding of elements

### ISSUE THREAD

**Issue by secretgspot** [ghostebony/svelte-virtual#3]
![image](https://user-images.githubusercontent.com/203323/200443360-5a486c7c-69d3-401f-8ba5-e98389649d28.png)

strange issue that appears when you scroll up and down and some fields turn bold, not sure why or where to even look for it. turning off {style} removes it but then it presents other set of issues

**Comment by ghostebony** [comment]
can you replicate on [repl](https://svelte.dev/repl) so can I investigate, thanks

**Comment by secretgspot** [comment]
sorry took so long, finally gotten to try to replicate it on repl but am unable, not sure if you discovered it and addressed it. Trying to replicate it I did ran into another one that's demonstrated in https://svelte.dev/repl/cf1129b3c76e4f8389eb1a0267c1f40f?version=3.53.1 with images loading

**Comment by ghostebony** [comment]
this one? #4

**Comment by ghostebony** [comment]
the only issue I see is this: 
![image](https://user-images.githubusercontent.com/47510020/203967860-0985feff-5587-4b96-872f-0903ca5fef58.png)

but is fixed by editing the `img` tag with `width="100"`
![image](https://user-images.githubusercontent.com/47510020/203968306-1412d7ba-c44c-4940-8ddf-06dc40f8bd8a.png)
